services:
  redis:
    image: redis:8.6
    restart: unless-stopped
    command: redis-server --requirepass ${PROD_REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${PROD_REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PROD_DB_NAME}
      - POSTGRES_USER=${PROD_DB_USER}
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PROD_DB_USER} -d ${PROD_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: poer1/photostudio-app:latest
    restart: unless-stopped

    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${PROD_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${PROD_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${PROD_DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=${PROD_REDIS_NAME}
      - SPRING_DATA_REDIS_PORT=${PROD_REDIS_PORT}
      - SPRING_DATA_PASSWORD=${PROD_REDIS_PASSWORD}
      - MANAGEMENT_SERVER_PORT=8081
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-https.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.app-https.entrypoints=websecure"
      - "traefik.http.routers.app-https.tls=true"
      - "traefik.http.routers.app-https.tls.certresolver=resolver"
      - "traefik.http.routers.app-https.service=app-service"

      - "traefik.http.routers.app-http.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.app-http.entrypoints=web"
      - "traefik.http.routers.app-http.service=app-service"

      - "traefik.http.services.app-service.loadbalancer.server.port=8080"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

    deploy:
      replicas: 2

  traefik:
    image: traefik:v3.7
    restart: unless-stopped
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER_ACME_EMAIL=${EMAIL_TO_NOTIFY}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt_data:/letsencrypt
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro

volumes:
  postgres_data:
  letsencrypt_data:
  redis_data:
