# options: mock, dev, prod
spring.profiles.active=dev
spring.application.name=server
spring.docker.compose.enabled=false

app.static-data.about-path=classpath:/data/about.json
app.static-data.rules-path=classpath:/data/rules.json
app.static-data.preview-path=classpath:/data/preview.json
app.static-data.base-path=classpath:/data/base.json
app.static-data.placeholder-path=/images/placeholder.png