spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.flyway.enabled=true
spring.docker.compose.enabled=true
spring.flyway.locations=classpath:db/migration/mock