spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.flyway.enabled=false
spring.docker.compose.enabled=true
spring.session.store-type=none