spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASSWORD}
spring.flyway.locations=classpath:db/migration/prod
spring.jpa.hibernate.ddl-auto=validate
spring.data.redis.host=${SPRING_DATA_HOST}
spring.data.redis.port=${SPRING_DATA_PORT}
spring.data.redis.password=${SPRING_DATA_PASSWORD}
spring.data.redis.timeout=5000ms