spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-only
spring.flyway.locations=classpath:db/migration/dev
spring.jpa.hibernate.ddl-auto=validate

spring.session.redis.namespace=spring:session
server.servlet.session.timeout=6h