name: Deploy

on:
  workflow_run:
    workflows: ["CI_build_push"]
    types: [completed]
    branches: [master]
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: CD

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/photostudio
            docker compose -f docker-compose.prod.yml pull app
            docker rollout -f docker-compose.prod.yml --wait-after-healthy 10 app
