name: CI

on:
  pull_request: 
    branches:
      - main
      - develop
  workflow_dispatch: 

permissions:
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    environment: CI_Tests
    
    env:
      TEST_DB_NAME: ${{ vars.TEST_DB_NAME }}
      TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
      TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
    
    steps:
      - run: echo "Checking out code"
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - run: echo "Setting up Java"
      - name: Setup Java JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: 21
          distribution: 'oracle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - run: echo "Building project"
      - name: Build project without PMD
        run: ./gradlew build -x pmdMain -x pmdTest

      - run: echo "Caching gradlew and build"
      - name: Cache gradlew and build
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - run: echo "Initiating tests"
      - name: Start tests
        run: ./gradlew test -x jacocoTestReport

      - name: Test report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: Tests
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit

      - run: echo "Generating JaCoCo reports"
      - run: ./gradlew jacocoTestReport
      - name: Generate JaCoCo report in GitHub
        uses: jjmrocha/jacoco-summary@v1.1.1

  pmd:
    runs-on: ubuntu-latest
    needs: test

    environment: CI_Tests
    
    env:
      TEST_DB_NAME: ${{ vars.TEST_DB_NAME }}
      TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
      TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
    
    steps:
      - run: echo "Checking out code"
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - run: echo "Setting up Java"
      - name: Setup Java JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: 21
          distribution: 'oracle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - run: echo "Granting cache back"
      - name: Grant cache
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - run: echo "Running PMD"
      - name: Run PMD
        run: ./gradlew pmdMain pmdTest
